package com.ipci.ngs.datacleaner.commonlib.agent;

public enum ConversationID {
	NONE,
	LIST_OF_READ_IN_PATH,
	CREATE_WORKSPACES,
	LOAD_WORKSPACES,
	VISUALIZE,
	RUN_PIPELINE,
	NOTIFY_LOG,
	NOTIFY_PROGRESS,
	NOTIFY_NEW_CLIENT,
	NOTIFY_CLIENT_LEFT,
	NOTIFY_WORKSPACE_STATUS,
	REQUEST_NOTIFICATION,
	NOTIFY_WORKER_FINISHED,
	REMOVE_WORKSPACE,
	NOTIFY_ERROR,
	CLEAN_WORKSPACE,
	REFRESH_WORKSPACE,
	REFRESH_WORKSPACE_OUTPUT,
	REQUEST_NOTIFICATION_SPECIFIC
}
